---
name: SDLC-Security
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs: # if commanted its work!
  # SCA:
  #   name: OSV Scanning project
  #   permissions:
  #     security-events: write
  #     actions: read
  #     contents: read
  #   uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v2.0.3
  #   with:
  #     scan-args: |-
  #       --lockfile=./requirements.txt
  #       --no-ignore
  #     results-file-name: "osv-results.sarif"
  #     upload-sarif: true
  #     fail-on-vuln: false
  # SAST:
  #   permissions:
  #     contents: read
  #     security-events: write
  #   name: Semgrep scanning
  #   runs-on: ubuntu-latest
  #   container:
  #     image: semgrep/semgrep
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v4
  #     - name: Scan project by semgrep
  #       run: semgrep scan -c ./semgrep-rules/ --sarif > ./reports/semgrep-results.sarif
  #       env:
  #         PYTHONUTF8: 1 # Without it impossible use RU encode
  #     - name: Upload artifact GitHub
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: semgrep-result
  #         path: ./reports/semgrep-results.sarif
  #         if-no-files-found: error
  #         retention-days: 1
  #     - name: SARIF to GitHub Security Dashboard
  #       uses: github/codeql-action/upload-sarif@v3
  #       with:
  #         sarif_file: ./reports/semgrep-results.sarif
  #       if: always() # Upload it in anyway
  IaC-Scan:
    name: Infrastructure as Code scanning
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run KICS Scan using config
        uses: checkmarx/kics-github-action@v2.1.10
        with:
          path: './'
          config_path: './kics.yml'
          ignore_on_exit: results
      - name: List files
        run: |
          ls -la
      - name: Upload artifact GitHub
        uses: actions/upload-artifact@v4
        with:
          name: kics-result
          path: './reports/'
          if-no-files-found: error
          retention-days: 1
      - name: SARIF to GitHub Security Dashboard
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./reports/results.sarif
        if: always()
    # steps:
    #   - name: Checkout
    #     uses: actions/checkout@v4
    #   - name: Upload OSV results to artifacts
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: OSV-result
    #       path: ./osv-results.sarif
    #       if-no-files-fount: error
    #       retention-days: 1
