---
name: SDLC-Security
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  SCA:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: OSV Scanning
        uses: google/osv-scanner-action@v2.0.3
        with:
          scan-args: |-
            --lockfile=./requirements.txt
            ./
          results-file-name: "osv-results.sarif"
          upload-sarif: true
          fail-on-vuln: true
    # steps:
    #   - name: Checkout
    #     uses: actions/checkout@v4
    #   - name: Upload OSV results to artifacts
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: OSV-result
    #       path: ./osv-results.sarif
    #       if-no-files-fount: error
    #       retention-days: 1
